version: '2'
services:
  eureka-service-repository:
    image: 585864718859.dkr.ecr.us-west-2.amazonaws.com/chinikom-user-service
    environment:
       - "SPRING_PROFILES_ACTIVE=mysql"
    cpu_shares: 100
    mem_limit: 1073741824
    ports:
      - "9003:9003"
      - "9004:9004"